import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import ConnectWalletButton from '../components/ConnectWalletButton'
import { GetBalanceTest } from '../components/GetBalanceTest'
import { GetERC721TransferTest } from '../components/GetERC721TransferTest'
import { SocialGraph } from '../components/graph/SocialGraph'

const Home: NextPage = () => {
  return (
    <div>

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SocialGraph/>
    </div>
  );
};

export default Home;
